title: Luke Currier

author: Luke Currier

navbar-links:
  Home: "index"
  Education: "school"
  Professional: "professional"
  Personal: "personal"
  Resume: "assets/files/resume.pdf"

avatar: /assets/img/shoulders.png

round-avatar: true

# Image in top left instead of text
# title-img: /assets/img/neuimage2.jpeg

social-network-links:
  email: "lukescurrier@gmail.com"
  github: lukecurrier
  twitter: lukescurrier
  linkedin: lucas-saltonstall-currier
  instagram: currier_luke
#  telephone: +16507395542
#  steam: Dastardi

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: false
  linkedin: true
  vk: false

# for a link in the footer
# url-pretty: "lukecurrier.github.io"

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
#edit_page_button: false

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
navbar-var-length: false

# keywords for SEO
keywords: "Luke,Currier,luke,currier"

navbar-col: "#738573"
navbar-text-col: "#404040"
navbar-border-col: "#738573"
page-col: "#fffbed"
text-col: "#404040"
link-col: "#404040"
hover-col: "#0085A1"
footer-col: "#738573"
footer-text-col: "#404040"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

mobile-theme-col: "#738573"

# can include additional CSS files - list here
#site-css:
#  - "/assets/css/custom-styles.css"

# common js files - list here
#site-js:
#  - "/assets/js/custom-script.js"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Output options (more information on Jekyll's site)
timezone: "America/Boston"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap